// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwwtQBRXld1pwPslpbd5zReJWbwyM_bo',
    appId: '1:416233407003:web:79e22348515ce624f66ebe',
    messagingSenderId: '416233407003',
    projectId: 'kwentong-kultura',
    authDomain: 'kwentong-kultura.firebaseapp.com',
    storageBucket: 'kwentong-kultura.firebasestorage.app',
    measurementId: 'G-FP4XMZBXYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBXAdxnu6JmpuyUClPhwfnP2sfw3xPeGM',
    appId: '1:416233407003:android:c7d57fa9b2d82011f66ebe',
    messagingSenderId: '416233407003',
    projectId: 'kwentong-kultura',
    storageBucket: 'kwentong-kultura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs13ePpUoT1KtUsN5Z91-vXcyeoEuh1nY',
    appId: '1:416233407003:ios:dc8cfba08e482d78f66ebe',
    messagingSenderId: '416233407003',
    projectId: 'kwentong-kultura',
    storageBucket: 'kwentong-kultura.firebasestorage.app',
    iosBundleId: 'com.example.kwentongKultura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs13ePpUoT1KtUsN5Z91-vXcyeoEuh1nY',
    appId: '1:416233407003:ios:dc8cfba08e482d78f66ebe',
    messagingSenderId: '416233407003',
    projectId: 'kwentong-kultura',
    storageBucket: 'kwentong-kultura.firebasestorage.app',
    iosBundleId: 'com.example.kwentongKultura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwwtQBRXld1pwPslpbd5zReJWbwyM_bo',
    appId: '1:416233407003:web:6f7b779dcf7b37abf66ebe',
    messagingSenderId: '416233407003',
    projectId: 'kwentong-kultura',
    authDomain: 'kwentong-kultura.firebaseapp.com',
    storageBucket: 'kwentong-kultura.firebasestorage.app',
    measurementId: 'G-Z2GFRYWWEY',
  );

}